Update ani-cli

diff --git a/ani-cli b/ani-cli
--- a/ani-cli
+++ b/ani-cli
@@ -107,7 +107,7 @@ version_info() {
 }
 
 update_script() {
-    update="$(curl -s -A "$agent" "https://raw.githubusercontent.com/candrapersada/ani-cli/FFmpeg/ani-cli")" || die "Connection error"
+    update="$(curl -s -A "$agent" "https://raw.githubusercontent.com/candrapersada/ani-cli/ffmpegpass2/ani-cli")" || die "Connection error"
     update="$(printf '%s\n' "$update" | diff -u "$0" -)"
     if [ -z "$update" ]; then
         printf "Script is up to date :)\n"
@@ -294,7 +294,8 @@ download() {
     [ -n "$subtitle" ] && ffmpegsubtitle="-i $subtitle -c:s mov_text"
     case $1 in
         *m3u8*)
-            ffmpeg -extension_picky 0 -referer "$m3u8_refr" -loglevel error -stats -i "$1" $ffmpegsubtitle$ffmpegconvter "$TMP_DIR/$2.mp4"
+            ffmpeg -extension_picky 0 -referer "$m3u8_refr" -loglevel error -stats -i "$1" $ffmpegsubtitle$ffmpegconvter -pass 1 -passlogfile "$TMP_DIR" && ffmpeg -extension_picky 0 -referer "$m3u8_refr" -loglevel error -stats -i "$1" $ffmpegsubtitle$ffmpegconvter -pass 2 -passlogfile "$TMP_DIR" "$TMP_DIR/$2.mp4"
+
             # embed subs into downloads
             # [ -n "$subtitle" ] && ffmpeg -loglevel error -i "$TMP_DIR/$2.mp4" -i "$subtitle" -c copy -c:s mov_text "$TMP_DIR/$2.bak.mp4" && mv "$TMP_DIR/$2.bak.mp4" "$TMP_DIR/$2.mp4"
             ;;
